name: Pull Requests
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installs global packages
        run: npm i -g eslint

      - name: Install dependencies
        run: npm ci

      - name: Lints the repository
        run: npm run lint
